export default doctorData = [
  {
    need: 'Tooth Problem',
    name: 'Tooth, Teeth, Dental, Dentist, Cavity, Toothache',
    info: 'Dr. Hema Jha',
    post: 'Dentist',
    contact: '9841815537',
  },
  {
    need: 'Tooth Problem',
    name: 'Tooth, Teeth, Dental, Dentist, Cavity, Toothache',
    info: 'Dr. Sanjay P Gupta',
    post: 'Dentist',
    contact: '9860042395',
  },
  {
    need: 'Tooth Problem',
    name: 'Tooth, Teeth, Dental, Dentist, Cavity, Toothache',
    info: 'Dr. Shrijana Shrestha',
    post: 'Dentist',
    contact: '9860305628',
  },
  {
    need: 'Tooth Problem',
    name: 'Tooth, Teeth, Dental, Dentist, Cavity, Toothache',
    info: 'Dr. Bisnu Bastola',
    post: 'Dentist',
    contact: '9841380608',
  },
  {
    need: 'Tooth Problem',
    name: 'Tooth, Teeth, Dental, Dentist, Cavity, Toothache',
    info: 'Dr. Sichan Shrestha',
    post: 'Dentist',
    contact: '9868910668',
  },
  {
    need: 'Physiotherapy',
    name: 'BackPain, NeckPain, BodyPain, Physiotherapy',
    info: 'Dr. Birason Rajbhandari',
    post: 'Physiotherapist',
    contact: '9851133590',
  },
  {
    need: 'Physiotherapy',
    name: 'BackPain, NeckPain, BodyPain, Physiotherapy',
    info: 'Dr. Bandana Acharya',
    post: 'Physiotherapist',
    contact: '9851243555',
  },
  {
    need: 'Physiotherapy',
    name: 'BackPain, NeckPain, BodyPain, Physiotherapy',
    info: 'Dr. Vimal Prajapati',
    post: 'Physiotherapist',
    contact: '9818760573',
  },
  {
    need: 'Eye Problem',
    name: 'Eye, Eyes, Optometry',
    info: 'Dr. Krishna Pokharel',
    post: 'Optometrist',
    contact: '9851061108',
  },
  {
    need: 'Eye Problem',
    name: 'Eye, Eyes, Optometry',
    info: 'Dr. Shyam Vyas',
    post: 'Ophthalmologist',
    contact: '01-4445746',
  },
  {
    need: 'Eye Problem',
    name: 'Eye, Eyes, Optometry',
    info: 'Dr. Apurva Ratna Tamrakar',
    post: 'Eye Surgeon',
    contact: '01-4269972',
  },
  {
    need: 'Eye Problem',
    name: 'Eye, Eyes, Optometry',
    info: 'Dr. Reeta Limbu',
    post: 'Optometrist',
    contact: '9843393583',
  },
  {
    need: 'Eye Problem',
    name: 'Eye, Eyes, Optometry',
    info: 'Dr. Ben Limbu',
    post: 'Eye Surgeon',
    contact: '9864592421',
  },
  {
    need: 'Eye Problem',
    name: 'Eye, Eyes, Optometry',
    info: 'Dr. Rachana Singh Rana',
    post: 'Cornea Specialist',
    contact: '01-4228531',
  },
  {
    need: 'Heart Problem',
    name: 'Heart, Cardiologist',
    info: 'Dr. Parag Karki',
    post: 'Cardiologist',
    contact: '9863393960',
  },
  {
    need: 'Heart Problem',
    name: 'Heart, Cardiologist',
    info: 'Dr. Om Murti Anil',
    post: 'Cardiologist',
    contact: '9843118902',
  },
  {
    need: 'Heart Problem',
    name: 'Heart, Cardiologist',
    info: 'Dr. Abhishek Thakur',
    post: 'Cardiologist',
    contact: '9801872311',
  },
  {
    need: 'Heart Problem',
    name: 'Heart, Cardiologist',
    info: 'Dr. Shuva J. B. Rana',
    post: 'MD Cardiologist',
    contact: '9843110554',
  },
  {
    need: 'Heart Problem',
    name: 'Heart, Cardiologist',
    info: 'Dr. Dipendra Singh',
    post: 'Registrar Cardiology',
    contact: '9841888956',
  },
  {
    need: 'Heart Problem',
    name: 'Heart, Cardiologist',
    info: 'Dr. Bijay Khadka',
    post: 'MD INTERNAL MEDICINE',
    contact: '9843243816',
  },
  {
    need: 'Skin Problem',
    name: 'SkinCare, Skin',
    info: 'Dr. Pramod Agarwal',
    post: 'Dermatologist',
    contact: '9851110443',
  },
  {
    need: 'Skin Problem',
    name: 'SkinCare, Skin',
    info: 'Dr. Romphuanjit',
    post: 'Dermatologist',
    contact: '9851149709',
  },
  {
    need: 'Skin Problem',
    name: 'SkinCare, Skin',
    info: 'Dr. Raj Bhandari',
    post: 'Dermatologist',
    contact: '9851037827',
  },
];
